"""
Seed 100 realistic bot users with cards.
Run: MONGODB_URL=<url> DATABASE_NAME=ariel python3 seed_bots.py
"""
import asyncio, os, random
from datetime import datetime, timedelta
from motor.motor_asyncio import AsyncIOMotorClient
from bson import ObjectId

MONGODB_URL = os.environ.get("MONGODB_URL", "mongodb://localhost:27017")
DB_NAME = os.environ.get("DATABASE_NAME", "ariel")

# ---------------------------------------------------------------------------
# 100 PERSONAS — name, username, email, subject, topic, pravatar seed
# ---------------------------------------------------------------------------
PERSONAS = [
  # --- Neuroscience / Medicine ---
  {"name":"Amara Osei","username":"amaraneuro","email":"amara.osei@ariel.bot","subject":"Neuroscience","topic":"Memory & Learning","img":1},
  {"name":"Isabella Ferreira","username":"bellamed","email":"isabella.ferreira@ariel.bot","subject":"Medicine","topic":"Pharmacology","img":2},
  {"name":"Ravi Krishnamurthy","username":"ravipharma","email":"ravi.krish@ariel.bot","subject":"Medicine","topic":"Drug Mechanisms","img":3},
  {"name":"Nadia Al-Hassan","username":"nadiapsych","email":"nadia.alhassan@ariel.bot","subject":"Psychiatry","topic":"Mental Health","img":4},
  {"name":"Luca Marchetti","username":"lucaneuro","email":"luca.marchetti@ariel.bot","subject":"Neurology","topic":"Neuroplasticity","img":5},
  {"name":"Yuki Tanaka","username":"yukiimmuno","email":"yuki.tanaka@ariel.bot","subject":"Immunology","topic":"Autoimmune Disease","img":6},
  {"name":"Fatima Benali","username":"fatimahealth","email":"fatima.benali@ariel.bot","subject":"Public Health","topic":"Epidemiology","img":7},
  {"name":"Marcus Thompson","username":"marcuscardio","email":"marcus.thompson@ariel.bot","subject":"Medicine","topic":"Cardiology","img":8},
  {"name":"Anya Petrov","username":"anyagenetics","email":"anya.petrov@ariel.bot","subject":"Genetics","topic":"CRISPR & Gene Editing","img":9},
  {"name":"James Okafor","username":"jamessurgery","email":"james.okafor@ariel.bot","subject":"Medicine","topic":"Surgery","img":10},
  # --- Physics / Mathematics ---
  {"name":"Erik Lindström","username":"erikphysics","email":"erik.lindstrom@ariel.bot","subject":"Physics","topic":"Quantum Mechanics","img":11},
  {"name":"Priya Sharma","username":"priyaquantum","email":"priya.sharma@ariel.bot","subject":"Physics","topic":"Quantum Computing","img":12},
  {"name":"Carlos Mendoza","username":"carlosmath","email":"carlos.mendoza@ariel.bot","subject":"Mathematics","topic":"Number Theory","img":13},
  {"name":"Liu Wei","username":"liuastro","email":"liu.wei@ariel.bot","subject":"Physics","topic":"Astrophysics","img":14},
  {"name":"Zara Ahmed","username":"zaraapplied","email":"zara.ahmed@ariel.bot","subject":"Mathematics","topic":"Linear Algebra","img":15},
  {"name":"Thomas Müller","username":"thomasparticle","email":"thomas.muller@ariel.bot","subject":"Physics","topic":"Particle Physics","img":16},
  {"name":"Keiko Yamamoto","username":"keikostats","email":"keiko.yamamoto@ariel.bot","subject":"Mathematics","topic":"Statistics & Probability","img":17},
  {"name":"Adebayo Adeyemi","username":"bayomath","email":"adebayo.adeyemi@ariel.bot","subject":"Mathematics","topic":"Topology","img":18},
  {"name":"Sophie Dubois","username":"sophiecosmos","email":"sophie.dubois@ariel.bot","subject":"Physics","topic":"Cosmology","img":19},
  {"name":"Andrei Volkov","username":"andreinumbers","email":"andrei.volkov@ariel.bot","subject":"Mathematics","topic":"Calculus","img":20},
  # --- History / Politics ---
  {"name":"Chioma Eze","username":"chiomahistory","email":"chioma.eze@ariel.bot","subject":"History","topic":"African History","img":21},
  {"name":"Omar Khaled","username":"omarmideast","email":"omar.khaled@ariel.bot","subject":"Political Science","topic":"Middle Eastern Politics","img":22},
  {"name":"Victoria Novak","username":"viceurohist","email":"victoria.novak@ariel.bot","subject":"History","topic":"European History","img":23},
  {"name":"Samuel Odhiambo","username":"sampolisci","email":"samuel.odhiambo@ariel.bot","subject":"Political Science","topic":"African Politics","img":24},
  {"name":"Mei Lin","username":"meiintrel","email":"mei.lin@ariel.bot","subject":"International Relations","topic":"China & Global Order","img":25},
  {"name":"Rafael Santos","username":"rafalatam","email":"rafael.santos@ariel.bot","subject":"Political Science","topic":"Latin American Politics","img":26},
  {"name":"Ingrid Larsen","username":"ingridpolphil","email":"ingrid.larsen@ariel.bot","subject":"Political Philosophy","topic":"Democracy & Governance","img":27},
  {"name":"Kwame Asante","username":"kwamepan","email":"kwame.asante@ariel.bot","subject":"History","topic":"Pan-Africanism","img":28},
  {"name":"Leila Moradi","username":"leilageo","email":"leila.moradi@ariel.bot","subject":"Political Science","topic":"Geopolitics","img":29},
  {"name":"Benjamin Cohen","username":"benconflict","email":"benjamin.cohen@ariel.bot","subject":"Political Science","topic":"Conflict & Peace Studies","img":30},
  # --- Economics / Finance ---
  {"name":"Aisha Diallo","username":"aishadeveco","email":"aisha.diallo@ariel.bot","subject":"Economics","topic":"Development Economics","img":31},
  {"name":"Henrik Johansson","username":"henrikbeheco","email":"henrik.johansson@ariel.bot","subject":"Economics","topic":"Behavioral Economics","img":32},
  {"name":"Priscilla Mensah","username":"priscyfinance","email":"priscilla.mensah@ariel.bot","subject":"Finance","topic":"Financial Markets","img":33},
  {"name":"David Kim","username":"davidmacro","email":"david.kim@ariel.bot","subject":"Economics","topic":"Macroeconomics","img":34},
  {"name":"Mariam Toure","username":"mariammicro","email":"mariam.toure@ariel.bot","subject":"Economics","topic":"Microeconomics","img":35},
  {"name":"Alex Petridis","username":"alexeconhist","email":"alex.petridis@ariel.bot","subject":"Economics","topic":"Economic History","img":36},
  {"name":"Nkechi Onyeka","username":"nkechimarkets","email":"nkechi.onyeka@ariel.bot","subject":"Finance","topic":"Investment & Valuation","img":37},
  {"name":"Tobias Weber","username":"tobiasmonetary","email":"tobias.weber@ariel.bot","subject":"Economics","topic":"Monetary Policy","img":38},
  {"name":"Camila Reyes","username":"camitrade","email":"camila.reyes@ariel.bot","subject":"Economics","topic":"International Trade","img":39},
  {"name":"Haruto Sato","username":"harutocorp","email":"haruto.sato@ariel.bot","subject":"Finance","topic":"Corporate Finance","img":40},
  # --- Psychology ---
  {"name":"Zoe Andersen","username":"zoecog","email":"zoe.andersen@ariel.bot","subject":"Psychology","topic":"Cognitive Psychology","img":41},
  {"name":"Kofi Boateng","username":"kofisocial","email":"kofi.boateng@ariel.bot","subject":"Psychology","topic":"Social Psychology","img":42},
  {"name":"Emma Walsh","username":"emmaclinical","email":"emma.walsh@ariel.bot","subject":"Psychology","topic":"Clinical Psychology","img":43},
  {"name":"Arjun Nair","username":"arjunneuro","email":"arjun.nair@ariel.bot","subject":"Psychology","topic":"Neuropsychology","img":44},
  {"name":"Maria Santos","username":"mariaedu","email":"maria.santos@ariel.bot","subject":"Psychology","topic":"Educational Psychology","img":45},
  {"name":"Noah Bergström","username":"noahevo","email":"noah.bergstrom@ariel.bot","subject":"Psychology","topic":"Evolutionary Psychology","img":46},
  {"name":"Amina Coulibaly","username":"aminadev","email":"amina.coulibaly@ariel.bot","subject":"Psychology","topic":"Developmental Psychology","img":47},
  {"name":"Jake Morrison","username":"jakesports","email":"jake.morrison@ariel.bot","subject":"Psychology","topic":"Sports Psychology","img":48},
  {"name":"Yuna Park","username":"yunapositive","email":"yuna.park@ariel.bot","subject":"Psychology","topic":"Positive Psychology","img":49},
  {"name":"Diana Popescu","username":"dianatrauma","email":"diana.popescu@ariel.bot","subject":"Psychology","topic":"Trauma & Resilience","img":50},
  # --- Computer Science / AI ---
  {"name":"Tariq Al-Rashid","username":"tariqml","email":"tariq.alrashid@ariel.bot","subject":"Computer Science","topic":"Machine Learning","img":51},
  {"name":"Aiko Suzuki","username":"aikocv","email":"aiko.suzuki@ariel.bot","subject":"Computer Science","topic":"Computer Vision","img":52},
  {"name":"Felix Osei","username":"felixcyber","email":"felix.osei@ariel.bot","subject":"Computer Science","topic":"Cybersecurity","img":53},
  {"name":"Natasha Ivanova","username":"natashasys","email":"natasha.ivanova@ariel.bot","subject":"Computer Science","topic":"Distributed Systems","img":54},
  {"name":"Raj Patel","username":"rajaiethics","email":"raj.patel@ariel.bot","subject":"Computer Science","topic":"AI Ethics","img":55},
  {"name":"Chloé Martin","username":"chloehci","email":"chloe.martin@ariel.bot","subject":"Computer Science","topic":"Human-Computer Interaction","img":56},
  {"name":"Emeka Nwosu","username":"emekablockchain","email":"emeka.nwosu@ariel.bot","subject":"Computer Science","topic":"Blockchain & Web3","img":57},
  {"name":"Lars Hansen","username":"larsquantum","email":"lars.hansen@ariel.bot","subject":"Computer Science","topic":"Quantum Algorithms","img":58},
  {"name":"Seo-Yeon Choi","username":"seoyeonnlp","email":"seoyeon.choi@ariel.bot","subject":"Computer Science","topic":"Natural Language Processing","img":59},
  {"name":"Gabriel Moreau","username":"gabrielrobots","email":"gabriel.moreau@ariel.bot","subject":"Computer Science","topic":"Robotics & Automation","img":60},
  # --- Law / Philosophy ---
  {"name":"Chidinma Obi","username":"chidilaw","email":"chidinma.obi@ariel.bot","subject":"Law","topic":"Constitutional Law","img":61},
  {"name":"Antoine Leclerc","username":"antoinephil","email":"antoine.leclerc@ariel.bot","subject":"Philosophy","topic":"Philosophy of Mind","img":62},
  {"name":"Zanele Dlamini","username":"zanelerights","email":"zanele.dlamini@ariel.bot","subject":"Law","topic":"Human Rights Law","img":63},
  {"name":"Hiroshi Nakamura","username":"hiroshilegal","email":"hiroshi.nakamura@ariel.bot","subject":"Law","topic":"Legal Philosophy","img":64},
  {"name":"Beatriz Alves","username":"beaintlaw","email":"beatriz.alves@ariel.bot","subject":"Law","topic":"International Law","img":65},
  {"name":"Elias Mensah","username":"eliascriminal","email":"elias.mensah@ariel.bot","subject":"Law","topic":"Criminal Justice","img":66},
  {"name":"Simone Russo","username":"simoneethics","email":"simone.russo@ariel.bot","subject":"Philosophy","topic":"Ethics & Moral Philosophy","img":67},
  {"name":"Adaeze Nwosu","username":"adaezecorp","email":"adaeze.nwosu@ariel.bot","subject":"Law","topic":"Corporate Law","img":68},
  {"name":"Viktor Sokolov","username":"viktorpolphil","email":"viktor.sokolov@ariel.bot","subject":"Philosophy","topic":"Political Philosophy","img":69},
  {"name":"Grace Wanjiru","username":"graceenvlaw","email":"grace.wanjiru@ariel.bot","subject":"Law","topic":"Environmental Law","img":70},
  # --- Biology / Chemistry ---
  {"name":"Femi Adeyemi","username":"femimolbio","email":"femi.adeyemi@ariel.bot","subject":"Biology","topic":"Molecular Biology","img":11},
  {"name":"Chen Xiao","username":"chenbiochem","email":"chen.xiao@ariel.bot","subject":"Chemistry","topic":"Biochemistry","img":12},
  {"name":"Lena Fischer","username":"lenaeco","email":"lena.fischer@ariel.bot","subject":"Biology","topic":"Ecology","img":13},
  {"name":"Oluwaseun Adeleke","username":"seunmicro","email":"seun.adeleke@ariel.bot","subject":"Biology","topic":"Microbiology","img":14},
  {"name":"Ana Gutierrez","username":"anaorgo","email":"ana.gutierrez@ariel.bot","subject":"Chemistry","topic":"Organic Chemistry","img":15},
  {"name":"Kweku Mensah","username":"kwekugene","email":"kweku.mensah@ariel.bot","subject":"Biology","topic":"Genetics","img":16},
  {"name":"Hana Novak","username":"hanacell","email":"hana.novak@ariel.bot","subject":"Biology","topic":"Cell Biology","img":17},
  {"name":"Diego Torres","username":"diegomarine","email":"diego.torres@ariel.bot","subject":"Biology","topic":"Marine Biology","img":18},
  {"name":"Precious Osei","username":"preciouspharma","email":"precious.osei@ariel.bot","subject":"Chemistry","topic":"Pharmacology","img":19},
  {"name":"Mia Andersson","username":"miaenvchem","email":"mia.andersson@ariel.bot","subject":"Chemistry","topic":"Environmental Chemistry","img":20},
  # --- Literature / Arts / Social ---
  {"name":"Adwoa Asante","username":"adwoalit","email":"adwoa.asante@ariel.bot","subject":"Literature","topic":"African Literature","img":21},
  {"name":"Matteo Romano","username":"matteoart","email":"matteo.romano@ariel.bot","subject":"Art History","topic":"Renaissance & Modern Art","img":22},
  {"name":"Blessing Chukwu","username":"blessingwrite","email":"blessing.chukwu@ariel.bot","subject":"Literature","topic":"Creative Writing","img":23},
  {"name":"Yuki Watanabe","username":"yukicomplit","email":"yuki.watanabe@ariel.bot","subject":"Literature","topic":"Comparative Literature","img":24},
  {"name":"Isabela Costa","username":"isabelaculture","email":"isabela.costa@ariel.bot","subject":"Sociology","topic":"Cultural Studies","img":25},
  {"name":"Patrick Kimani","username":"patrickjourn","email":"patrick.kimani@ariel.bot","subject":"Journalism","topic":"Media & Society","img":26},
  {"name":"Astrid Nilsson","username":"astridmedia","email":"astrid.nilsson@ariel.bot","subject":"Sociology","topic":"Media Studies","img":27},
  {"name":"Tunde Bakare","username":"tundefilm","email":"tunde.bakare@ariel.bot","subject":"Art History","topic":"Film & Cinema","img":28},
  {"name":"Layla Hassan","username":"laylaartphil","email":"layla.hassan@ariel.bot","subject":"Philosophy","topic":"Aesthetics & Art","img":29},
  {"name":"Miriam Osei","username":"miriamsocio","email":"miriam.osei@ariel.bot","subject":"Sociology","topic":"Social Inequality","img":30},
  # --- Business / Entrepreneurship ---
  {"name":"Seun Adesanya","username":"seunstartup","email":"seun.adesanya@ariel.bot","subject":"Business","topic":"Entrepreneurship","img":31},
  {"name":"Ji-Ho Lee","username":"jihomarketing","email":"jiho.lee@ariel.bot","subject":"Business","topic":"Marketing Strategy","img":32},
  {"name":"Amara Traoré","username":"amaraimpact","email":"amara.traore@ariel.bot","subject":"Business","topic":"Social Enterprise","img":33},
  {"name":"Pieter van den Berg","username":"pieterstrat","email":"pieter.vdberg@ariel.bot","subject":"Business","topic":"Corporate Strategy","img":34},
  {"name":"Nneka Obiora","username":"nnekainnov","email":"nneka.obiora@ariel.bot","subject":"Business","topic":"Innovation & Design Thinking","img":35},
  {"name":"Marcus Lindberg","username":"marcuslead","email":"marcus.lindberg@ariel.bot","subject":"Business","topic":"Leadership","img":36},
  {"name":"Fatou Diop","username":"fatousustain","email":"fatou.diop@ariel.bot","subject":"Business","topic":"Sustainable Business","img":37},
  {"name":"Yusuf Mwangi","username":"yusuftech","email":"yusuf.mwangi@ariel.bot","subject":"Business","topic":"Tech Startups & VC","img":38},
  {"name":"Valentina Cruz","username":"valebrand","email":"valentina.cruz@ariel.bot","subject":"Business","topic":"Brand Management","img":39},
  {"name":"Ibrahim Sawadogo","username":"ibrahiminvest","email":"ibrahim.sawadogo@ariel.bot","subject":"Business","topic":"Impact Investment","img":40},
]

# ---------------------------------------------------------------------------
# CARDS — rich content per subject
# ---------------------------------------------------------------------------
CARDS_BY_SUBJECT = {
  "Neuroscience": [
    {"question":"What is the default mode network (DMN) and why does it matter?","answer":"The DMN is a set of interconnected brain regions (medial prefrontal cortex, posterior cingulate cortex, angular gyrus) that activates during rest, self-referential thought, and mind-wandering. It matters because overactivity is linked to depression and anxiety, while healthy DMN function underlies creativity, empathy, and autobiographical memory.","explanation":"Understanding DMN dysregulation has transformed how we think about psychiatric disorders — it's not about 'doing nothing' when the DMN activates, but about the quality of internal thought.","topic":"Memory & Learning","caption":"Been obsessing over DMN research lately. The fact that our brain's 'resting state' is actually the most metabolically expensive thing we do completely changed how I think about boredom and mind-wandering 🧠 rest ≠ doing nothing"},
    {"question":"How does long-term potentiation (LTP) underpin memory formation?","answer":"LTP is a long-lasting strengthening of synapses between neurons that fire together repeatedly. It involves NMDA receptor activation, calcium influx, AMPA receptor insertion, and ultimately structural changes to dendritic spines. Hebb's rule — 'neurons that fire together wire together' — is the conceptual foundation.","explanation":"LTP is the cellular basis of learning. Without it, new information cannot be consolidated from short-term to long-term memory.","topic":"Memory & Learning","caption":"Studied LTP for my neuropharmacology exam yesterday. What I find wild is that a single intense experience can trigger LTP fast enough to form a lasting memory — that's literally how trauma and joy both get 'written' into the brain"},
    {"question":"What distinguishes declarative from procedural memory at the neural level?","answer":"Declarative (explicit) memory depends on the hippocampus and medial temporal lobe — it encodes facts and events. Procedural (implicit) memory relies on the basal ganglia and cerebellum — it encodes skills and habits. This is why patients with hippocampal damage (like H.M.) can still learn motor tasks but cannot form new conscious memories.","explanation":"The famous case of patient H.M. was pivotal. He couldn't form new episodic memories but could still learn to trace a star in a mirror — evidence of intact procedural systems.","topic":"Memory & Learning","caption":"Reading about H.M. again and honestly it never gets less profound. Imagine being unable to form a single new memory after age 27 — yet your hands still learn things your mind can't recall. The brain is something else 🧬"},
    {"question":"What is neuroplasticity and what are its limits?","answer":"Neuroplasticity is the brain's ability to reorganize itself by forming new neural connections throughout life. It includes synaptic plasticity (changes in synapse strength), structural plasticity (growth of new dendrites/axons), and neurogenesis (birth of new neurons, mainly in hippocampus). Limits include: critical periods in development, age-related decline in plasticity factors like BDNF, and the metabolic cost of rewiring.","explanation":"Plasticity is not unlimited — the brain prioritises stability as we age. This is why learning new languages or instruments is harder (not impossible) after childhood.","topic":"Neuroplasticity","caption":"Something my professor said that stuck with me: plasticity is the brain's way of surviving the world, not just adapting to a classroom. Every new experience physically changes your neural architecture — good and bad ones equally 🔬"},
    {"question":"How do glial cells support neuron function — and what happens when they fail?","answer":"Glial cells (astrocytes, oligodendrocytes, microglia) maintain ionic balance, provide metabolic support, form myelin sheaths, and prune synapses. When they fail: astrocyte dysfunction contributes to ALS and Alzheimer's; demyelination causes multiple sclerosis; microglial overactivation drives neuroinflammation in depression and Parkinson's.","explanation":"For decades we thought neurons were the only important cells in the brain. We now know glia are co-pilots — and their dysfunction is central to almost every major neurological disease.","topic":"Memory & Learning","caption":"My whole perspective on brain disease changed when I realised glia aren't just support cells — they are active participants in cognition. MS, ALS, even depression all involve glial pathology. This area of research is severely underfunded"},
  ],
  "Medicine": [
    {"question":"What is the mechanism of action of beta-blockers and their key clinical uses?","answer":"Beta-blockers competitively antagonise catecholamines (adrenaline, noradrenaline) at beta-adrenergic receptors. Beta-1 blockade reduces heart rate and contractility (cardiac output ↓). Clinical uses: hypertension, heart failure (paradoxically — reduces remodelling), angina, arrhythmias, post-MI, anxiety (off-label), hyperthyroidism, migraine prophylaxis.","explanation":"The paradox of using beta-blockers in heart failure — once contraindicated, now first-line — is one of medicine's most important lessons about how pathophysiology guides treatment evolution.","topic":"Pharmacology","caption":"Pharmacology exam next week and beta-blockers are still tripping me up. The fact that they were once contraindicated in heart failure and are now first-line therapy tells you everything about how humbling medicine can be — what we 'know' keeps changing 💊"},
    {"question":"Explain the coagulation cascade and where common anticoagulants act.","answer":"The cascade has two pathways: Extrinsic (tissue factor → Factor VII) and Intrinsic (XIIa → XIa → IXa). Both converge at Factor X → thrombin → fibrin clot. Warfarin inhibits Vitamin K-dependent factors (II, VII, IX, X). Heparin potentiates antithrombin III. DOACs: rivaroxaban/apixaban inhibit Xa; dabigatran inhibits thrombin directly.","explanation":"Understanding the cascade is essential for managing bleeding risk in surgery, anticoagulation reversal, and interpreting coagulation tests (PT, APTT).","topic":"Drug Mechanisms","caption":"Nothing humbles you like teaching the coagulation cascade to first-years and realising you've been explaining it wrong 😅 drew it out fresh today — sharing for anyone who needs a clean breakdown"},
    {"question":"What is the pathophysiology of type 2 diabetes and why is it progressive?","answer":"T2DM begins with insulin resistance (cells fail to respond to insulin, especially muscle and liver). The pancreas compensates by increasing insulin secretion. Over years, beta-cell exhaustion occurs. Progressive because: chronic hyperglycaemia causes glucotoxicity and lipotoxicity, further damaging beta cells; inflammation and oxidative stress drive ongoing loss of beta-cell mass.","explanation":"T2DM is progressive by nature — most patients will eventually need insulin despite starting on oral agents. Lifestyle intervention in the early stages can genuinely reverse insulin resistance.","topic":"Drug Mechanisms","caption":"Working in the outpatient clinic this week and seeing patients who've had T2DM for 20 years is a reminder of why early intervention matters so much. The disease is progressive — but it doesn't have to be if caught and managed early. Education is medicine."},
    {"question":"What are the SIRS criteria and how do they relate to sepsis?","answer":"SIRS (Systemic Inflammatory Response Syndrome): ≥2 of — temp >38°C or <36°C, HR >90, RR >20 or PaCO2 <32, WBC >12,000 or <4,000. Sepsis = SIRS + confirmed/suspected infection with organ dysfunction. Modern definition (Sepsis-3): life-threatening organ dysfunction caused by dysregulated host response to infection (SOFA score ≥2).","explanation":"The shift from SIRS-based to SOFA-based sepsis definition reflects a better understanding — sepsis is fundamentally about organ dysfunction, not just inflammation.","topic":"Surgery","caption":"Sepsis kills millions every year and the most preventable deaths are from delayed recognition. The SOFA criteria exist for a reason — every hour of delayed antibiotics increases mortality by ~7%. Learned this the hard way on a night shift I won't forget."},
    {"question":"How does aspirin's mechanism differ from other NSAIDs?","answer":"Aspirin irreversibly acetylates cyclooxygenase (COX-1 and COX-2), permanently inhibiting them. Other NSAIDs (ibuprofen, naproxen) reversibly inhibit COX. Because platelets have no nucleus and cannot synthesise new COX, aspirin's antiplatelet effect lasts the platelet's lifetime (~10 days). This is why low-dose aspirin is uniquely effective for cardiovascular prophylaxis.","explanation":"The irreversibility is everything. One molecule of aspirin permanently disables one COX enzyme in a platelet that will never replace it — making aspirin one of the most impactful drugs per milligram ever discovered.","topic":"Pharmacology","caption":"Aspirin is genuinely one of the most remarkable drugs ever discovered. Cheap, old, still irreplaceable for cardiovascular protection. The irreversible COX inhibition mechanism is something every student needs to understand deeply, not just memorise 💊"},
  ],
  "Physics": [
    {"question":"What is quantum entanglement and why did Einstein call it 'spooky action at a distance'?","answer":"Quantum entanglement is a phenomenon where two particles become correlated such that the quantum state of one instantly influences the other, regardless of distance. Einstein called it 'spooky' because it appeared to violate locality — information seemed to travel faster than light. Bell's theorem (1964) and subsequent experiments confirmed entanglement is real, but no information is actually transmitted — the correlations are built in at the moment of entanglement.","explanation":"Entanglement doesn't allow faster-than-light communication, which preserves special relativity. But it does enable quantum cryptography and quantum computing, technologies that are now very real.","topic":"Quantum Mechanics","caption":"Spent the morning re-reading Bell's theorem and I'm still not over it. The fact that we've experimentally confirmed that the universe is non-local at the quantum level is one of the most profound things physics has ever established 🔭 Einstein was wrong about this one"},
    {"question":"Explain the Heisenberg Uncertainty Principle — what does it actually mean?","answer":"The HUP states that the more precisely you know a particle's position, the less precisely you can know its momentum, and vice versa: Δx·Δp ≥ ℏ/2. This is NOT about measurement disturbance — it's a fundamental property of quantum systems. A particle doesn't have a definite position AND momentum simultaneously; the uncertainty is ontological, not epistemological.","explanation":"The common misconception is that we're just disturbing the particle when we measure it. The HUP says something deeper: those conjugate properties don't exist precisely at the same time, even in principle.","topic":"Quantum Mechanics","caption":"The HUP misconception drives me crazy — it's not about the measuring instrument being clumsy. It's about the nature of reality itself. A quantum particle doesn't have a precise position AND momentum at the same time. Full stop. Ontological uncertainty, not observer error."},
    {"question":"What is dark matter and what evidence do we have for its existence?","answer":"Dark matter is a hypothetical form of matter that doesn't interact electromagnetically (so can't be seen) but exerts gravitational effects. Evidence: (1) Galaxy rotation curves — stars at galaxy edges orbit too fast for visible mass alone; (2) Gravitational lensing — bends light more than visible matter accounts for; (3) Cosmic microwave background — structure formation requires more matter than we observe; (4) Bullet Cluster — shows matter separated from gas during galaxy collision.","explanation":"Despite decades of searching, no dark matter particle has been directly detected. It remains one of the biggest open problems in physics — we know it's there, we just don't know what it is.","topic":"Astrophysics","caption":"The Bullet Cluster remains the single most convincing piece of evidence for dark matter to me. You can literally see the gravitational mass separated from the normal matter after two galaxy clusters collided. It's not a theoretical construct at that point — it's an observation 🌌"},
    {"question":"What is the Standard Model and what does it leave unexplained?","answer":"The Standard Model describes all known fundamental particles (quarks, leptons, gauge bosons) and three of the four fundamental forces (electromagnetic, weak, strong). It leaves unexplained: gravity (no quantum theory of gravity), dark matter, dark energy, matter-antimatter asymmetry, neutrino masses, and why there are three generations of particles.","explanation":"The Standard Model is the most precisely tested scientific theory ever — predictions confirmed to 12 decimal places. Yet it describes only ~5% of the universe's content.","topic":"Particle Physics","caption":"We have the most precisely tested theory in the history of science and it only describes 5% of what exists. The arrogance of thinking physics is 'almost done' after the Higgs discovery is genuinely baffling to me. We haven't even started."},
    {"question":"How does general relativity describe gravity differently from Newton?","answer":"Newton described gravity as a force acting at a distance. Einstein's GR describes gravity as the curvature of spacetime caused by mass-energy. Objects follow geodesics (shortest paths through curved spacetime) — what we perceive as gravitational attraction is actually objects moving straight through curved space. Predictions unique to GR: gravitational time dilation, gravitational waves, black holes, light deflection by gravity.","explanation":"LIGO's detection of gravitational waves in 2015 was a direct confirmation of GR's prediction — ripples in spacetime from merging black holes, exactly as Einstein's equations described.","topic":"Quantum Mechanics","caption":"Gravitational waves. Let that sink in. We detected ripples in spacetime from two black holes that merged 1.3 billion years ago — an event so violent it briefly distorted Earth by 1/1000th the diameter of a proton. And we measured it. GR is not just beautiful, it's experimentally bulletproof 🌊"},
  ],
  "Mathematics": [
    {"question":"What is Gödel's Incompleteness Theorem and why is it philosophically significant?","answer":"Gödel's First Incompleteness Theorem states that any consistent formal system powerful enough to describe arithmetic contains statements that are true but unprovable within the system. The Second Theorem states such a system cannot prove its own consistency. Philosophically: it limits what mathematics can achieve through formal proof and undermined Hilbert's program of finding a complete, consistent foundation for all mathematics.","explanation":"Gödel essentially proved that mathematical truth is larger than mathematical proof — there will always be true things we cannot prove from any given set of axioms.","topic":"Number Theory","caption":"Every time I explain Gödel's theorem to someone and watch their face change, I remember why I study mathematics. The idea that there are truths that are permanently beyond formal proof — not because we're not smart enough, but because of the nature of logic itself — is one of the most humbling ideas in intellectual history"},
    {"question":"What is the Riemann Hypothesis and why does it matter?","answer":"The Riemann Hypothesis states that all non-trivial zeros of the Riemann zeta function ζ(s) lie on the critical line Re(s) = 1/2. It matters because the distribution of prime numbers is deeply connected to these zeros — proving or disproving RH would transform our understanding of prime distribution. It remains one of the Millennium Prize Problems ($1 million prize).","explanation":"Primes are the atoms of arithmetic. Understanding their distribution is fundamental — and RH is the key. Cryptography, number theory, and physics (quantum chaos) all have stakes in its resolution.","topic":"Number Theory","caption":"Spent 4 hours today just trying to understand the connection between RH and prime distribution properly. Not to solve it — just to understand why it matters. The deeper you go, the more you realise mathematics is one coherent organism where everything connects to everything else"},
    {"question":"What is the difference between countable and uncountable infinity?","answer":"Cantor showed not all infinities are equal. ℕ (natural numbers), ℤ, ℚ are countably infinite — they can be put in 1-1 correspondence with ℕ. ℝ (real numbers) is uncountably infinite — Cantor's diagonal argument proves no such correspondence exists. There are strictly more real numbers than natural numbers, even though both are infinite.","explanation":"This was deeply controversial in Cantor's time — Kronecker called him a 'corruptor of youth.' Now it's foundational to set theory and mathematics as a whole.","topic":"Number Theory","caption":"Cantor's diagonal argument is the most elegant proof I have ever seen. Two infinities, one strictly larger than the other, proved with a one-page argument that any motivated teenager could follow. Mathematics is art 🎨"},
  ],
  "Political Science": [
    {"question":"What is the difference between realism and liberalism in international relations theory?","answer":"Realism: states are primary actors, international system is anarchic, states pursue power and security above all, cooperation is limited and fragile. Key thinkers: Thucydides, Machiavelli, Morgenthau, Waltz. Liberalism: cooperation is possible through institutions, trade, and shared norms; democracy promotes peace (Democratic Peace Theory); institutions like UN/WTO reduce conflict. Key thinkers: Kant, Woodrow Wilson, Keohane.","explanation":"Both theories have predictive failures — realism couldn't explain the peaceful end of the Cold War; liberalism underestimated the durability of authoritarian regimes. Reality usually lies between them.","topic":"Middle Eastern Politics","caption":"Teaching myself IR theory this semester and the realist-liberal debate is genuinely more relevant in 2024 than ever. Russian invasion of Ukraine: realists say 'told you so' about NATO expansion; liberals say 'told you so' about the importance of institutions. Both are half-right."},
    {"question":"What caused the Arab Spring and why did most revolutions fail to produce stable democracies?","answer":"Causes: economic grievances (youth unemployment, inequality), corruption, authoritarian repression, social media enabling coordination, food price spikes (2010-11). Most transitions failed because: lack of organised political parties to channel revolutionary energy, military/deep state resistance (Egypt), sectarian divisions exploited (Syria, Libya, Bahrain), external intervention, and weak civil society institutions.","explanation":"Tunisia is the partial exception — it had stronger pre-existing civil society institutions (trade unions, bar association) that brokered compromises. Even Tunisia has since had democratic backsliding under Saied.","topic":"Middle Eastern Politics","caption":"The Arab Spring is a masterclass in the gap between toppling a dictator and building a democracy. Mubarak falling in 18 days felt like the beginning of something — but removing a dictator and removing a system are entirely different things. Egypt 2013 proved that. 🔥"},
    {"question":"What is democratic backsliding and what are its early warning signs?","answer":"Democratic backsliding is the gradual erosion of democratic norms and institutions by elected leaders — distinct from outright coups. Warning signs: executive aggrandisement (concentrating power via legal means), attacks on judiciary independence, delegitimising media and opposition, politicising security forces, manipulating electoral rules. Examples: Hungary (Orbán), Turkey (Erdoğan), India (concerns raised re: BJP).","explanation":"Modern democratic erosion is subtle — it often happens through legal mechanisms, making it harder to resist than a tank in the street. By the time it's obvious, institutions are already compromised.","topic":"Democracy & Governance","caption":"Levitsky and Ziblatt's 'How Democracies Die' should be required reading everywhere right now. Democracies rarely end with a bang — they end with a thousand legal paper cuts from elected leaders who figured out you can dismantle democracy using democracy's own tools. Very relevant in 2024."},
    {"question":"What are the main theories explaining why some countries remain trapped in poverty?","answer":"Geography hypothesis (Diamond, Sachs): tropical diseases, poor soils, landlocked terrain create structural disadvantages. Institutions hypothesis (Acemoglu, Robinson): extractive vs. inclusive institutions determine long-run growth — better predictor than geography. Cultural hypothesis (Weber, Landes): values, trust, work ethic matter. Dependency theory: colonial and neo-colonial extraction keeps periphery poor. Consensus leans toward institutions as most powerful explanatory variable.","explanation":"'Why Nations Fail' (Acemoglu & Robinson) makes the strongest empirical case: same geography, different institutions → different outcomes (e.g., North/South Korea, East/West Germany).","topic":"African Politics","caption":"Been reading Acemoglu and Robinson alongside Fanon lately and the conversation between them is fascinating. One says institutions are everything; the other says you can't separate institutions from the colonial process that designed them to extract, not develop. Both are right. 📚"},
    {"question":"How has China's Belt and Road Initiative reshaped global geopolitics?","answer":"The BRI (launched 2013) involves infrastructure investment (ports, roads, railways, energy) across 140+ countries totalling $1 trillion+. Geopolitical effects: extends Chinese soft power and strategic access (e.g., Hambantota port in Sri Lanka), creates debt leverage over developing nations, counters US alliance networks, reorients global trade flows toward China. Critics cite 'debt trap diplomacy'; defenders note genuine infrastructure gaps filled.","explanation":"Whether BRI represents genuine development cooperation or strategic encirclement depends on whose lens you use. The empirical reality is probably both simultaneously.","topic":"China & Global Order","caption":"Spent the week mapping BRI projects in East Africa for a paper. What struck me most isn't the debt trap narrative — it's how little African governments have been able to negotiate. The information asymmetry is enormous. A port for Chinese goods vs. genuine development: the difference matters enormously 🌍"},
  ],
  "Economics": [
    {"question":"What is Modern Monetary Theory (MMT) and what are its main criticisms?","answer":"MMT argues that monetarily sovereign governments (that issue their own currency) cannot become insolvent in their own currency — they can always print money to pay debt. Therefore, the binding constraint on spending is inflation, not solvency. Policy implication: deficits don't matter until inflation appears, at which point taxes (not borrowing) are the tool to reduce demand. Criticisms: understates inflation risk, undermines bond market discipline, politically misused to justify unlimited spending.","explanation":"MMT is not a policy position — it's a description of how monetary systems work. The disagreement is about what follows from that description.","topic":"Macroeconomics","caption":"Every time I explain MMT, someone says 'but Zimbabwe!' and every time I have to explain that monetary sovereignty and political will to control inflation are two completely different things 😅 MMT isn't saying print money forever — it's saying the constraint is inflation, not arithmetic. Important distinction."},
    {"question":"What is the Lucas Critique and why did it revolutionise macroeconomic modelling?","answer":"Robert Lucas (1976) argued that traditional econometric models fail when used to guide policy, because people's behaviour changes in response to policy itself. If a government exploits a statistical relationship between inflation and unemployment (Phillips Curve), people will adjust expectations and the relationship disappears. Solution: build models based on deep structural parameters (preferences, technology) that don't change with policy.","explanation":"The Lucas Critique led to the development of DSGE (Dynamic Stochastic General Equilibrium) models — now standard in central banking — and elevated rational expectations to the heart of macroeconomics.","topic":"Macroeconomics","caption":"The Lucas Critique is one of those ideas that seems obvious in hindsight but was genuinely revolutionary. The government can't exploit a correlation forever because people are not passive. Rational expectations changed everything about how we model policy. Still relevant every time someone cites a historical correlation as proof of future policy effectiveness."},
    {"question":"Why do economists study randomised controlled trials (RCTs) in development economics?","answer":"RCTs randomly assign treatment and control groups to rigorously test whether an intervention (microfinance, cash transfers, deworming, etc.) causes an outcome rather than correlating with it. Duflo, Banerjee, and Kremer won the 2019 Nobel Prize for applying this method to poverty reduction. RCTs solve selection bias — the main problem with observational data in development economics.","explanation":"Before RCTs became mainstream, development economics relied heavily on cross-country regressions plagued by endogeneity. RCTs brought the discipline's rigour closer to medicine. They also have limitations: external validity (results from Kenya may not apply to Bangladesh) and ethical concerns about withholding treatment.","topic":"Development Economics","caption":"Development economics before RCTs vs. after RCTs is a before/after story of an entire field maturing. Does microfinance actually work? We thought so for decades. RCTs showed the reality is far more mixed. Humbling — and necessary. Science should update on evidence, not ideology 📊"},
    {"question":"What is the difference between nominal and real interest rates and why does it matter?","answer":"Nominal rate = stated interest rate. Real rate = nominal rate − inflation (Fisher equation). Matters because: (1) Borrowers and lenders care about purchasing power, not nominal numbers. Real negative interest rates mean savers are losing money in real terms. (2) Central banks target real rates to influence economic behaviour. (3) In hyperinflation, nominal rates look high but real rates can be catastrophically negative.","explanation":"The Fisher effect describes how nominal rates adjust to expected inflation in the long run. In the short run, central banks can influence real rates — which is the mechanism of monetary policy.","topic":"Monetary Policy","caption":"Explaining real vs. nominal interest rates to my younger brother yesterday and realised this is the single most practically important economic concept for everyday life. Your savings account paying 4% sounds good until inflation is 5% — you're getting poorer in real terms. This should be taught in secondary school universally."},
  ],
  "Psychology": [
    {"question":"What is cognitive dissonance and how do people resolve it?","answer":"Cognitive dissonance (Festinger, 1957) is the psychological discomfort of holding contradictory beliefs or when behaviour conflicts with beliefs. Resolution strategies: (1) Change the behaviour, (2) Change the belief to align with the behaviour, (3) Add new cognitions to rationalise the inconsistency. Most people choose option 3 — rationalisation. This underlies confirmation bias, post-purchase rationalisation, and political belief persistence.","explanation":"The most important insight: people don't primarily change their behaviour to match their beliefs — they change their beliefs to match their behaviour, then construct reasons why it was right all along.","topic":"Cognitive Psychology","caption":"Cognitive dissonance is the most underrated concept in psychology for understanding everyday human behaviour. We don't think ourselves into new actions — we act, then rationalise. Understanding this changed how I approach my own decisions completely 🧠"},
    {"question":"What is the fundamental attribution error?","answer":"The FAE (Ross, 1977) is the tendency to overestimate dispositional (personality/character) factors and underestimate situational factors when explaining others' behaviour. 'He's lazy' rather than 'he's been working two jobs.' Importantly, we show the actor-observer asymmetry: we attribute our own behaviour to situations ('I was stressed') but others' to character ('she's irresponsible').","explanation":"The FAE is the basis of a lot of social injustice — assuming poverty reflects laziness, crime reflects character rather than circumstances. Milgram and Zimbardo's work dramatically demonstrated how powerful situations are over dispositions.","topic":"Social Psychology","caption":"The fundamental attribution error might be the most practically important finding in social psychology. Every time you judge someone harshly, ask what situation they're in that you can't see. It doesn't excuse everything but it explains most of it. Milgram proved that ordinary people do extraordinary evil under the right situational pressure."},
    {"question":"What is attachment theory and what are the four attachment styles?","answer":"Bowlby's attachment theory: humans have an evolutionary need for close emotional bonds with caregivers. Secure attachment (responsive caregiving) → comfortable with intimacy and autonomy. Anxious/Preoccupied (inconsistent caregiving) → clings to relationships, fears abandonment. Dismissive-Avoidant (emotionally unavailable caregiving) → suppresses attachment needs. Fearful-Avoidant/Disorganised (frightening caregiving) → wants closeness but fears it.","explanation":"Attachment styles formed in childhood shape adult relationship patterns. They're not destiny — earned security (developing security through therapy or healthy relationships) is well-documented.","topic":"Developmental Psychology","caption":"Understanding attachment theory didn't just change how I study psychology — it changed how I understand my own relationships. And the most important finding might be that attachment styles can change. Earned security is real. Therapy and good relationships can genuinely rewrite relational patterns formed in childhood 💙"},
    {"question":"What does the psychology of motivation tell us about intrinsic vs. extrinsic motivation?","answer":"Intrinsic motivation: doing something for its inherent satisfaction. Extrinsic: for external rewards/consequences. Deci & Ryan's Self-Determination Theory identifies three innate needs: competence, autonomy, relatedness. Key finding: adding extrinsic rewards to already-intrinsically motivated behaviour can undermine it (overjustification effect). This has major implications for education, management, and parenting.","explanation":"The overjustification effect explains why paying children to read can make them less interested in reading. External rewards shift the perceived reason for the behaviour from internal to external.","topic":"Educational Psychology","caption":"The overjustification effect should be known by every teacher and parent. When you pay a child for something they already love doing, you can kill the love. Grades have this problem. We've built entire educational systems around extrinsic motivation and then wonder why students lose curiosity 😔"},
  ],
  "Computer Science": [
    {"question":"What is the difference between supervised, unsupervised, and reinforcement learning?","answer":"Supervised learning: model trained on labelled data (input-output pairs) to predict outputs for new inputs. Examples: image classification, spam detection. Unsupervised learning: model finds patterns in unlabelled data. Examples: clustering, dimensionality reduction, generative models. Reinforcement learning: agent learns by interacting with environment, receiving rewards/penalties. Examples: game-playing AI (AlphaGo), robotics, recommendation systems.","explanation":"Most real-world ML applications combine approaches. LLMs like GPT use unsupervised pre-training followed by supervised fine-tuning and RLHF (Reinforcement Learning from Human Feedback).","topic":"Machine Learning","caption":"The distinction between these three paradigms seems academic until you realise it determines almost every architectural decision in a real ML project. What data do you have? What's your reward signal? What are you optimising? These questions have very different answers depending on which paradigm you're in 💻"},
    {"question":"What are the main attack vectors in cybersecurity and how are they mitigated?","answer":"(1) Social engineering (phishing, pretexting) — mitigation: user training, MFA, email filtering. (2) SQL injection — mitigation: parameterised queries, input validation. (3) XSS (cross-site scripting) — mitigation: output encoding, CSP headers. (4) Man-in-the-middle — mitigation: TLS/HTTPS, certificate pinning. (5) Zero-day exploits — mitigation: defence in depth, monitoring, rapid patching. (6) Supply chain attacks — mitigation: dependency auditing, signed packages.","explanation":"The weakest link in almost every breach is human — social engineering remains the most successful attack vector. Technical controls matter, but security culture matters more.","topic":"Cybersecurity","caption":"Still thinking about the SolarWinds attack. The most sophisticated state-sponsored hack in history didn't start with a zero-day — it started with a routine software update. Supply chain security is the hardest problem in cybersecurity right now and most organisations aren't close to solving it 🔐"},
    {"question":"What is the blockchain trilemma and why does it matter for Web3?","answer":"Vitalik Buterin's blockchain trilemma: you can optimise for at most two of three properties simultaneously — decentralisation, security, scalability. Bitcoin prioritises decentralisation + security (slow, limited throughput). Ethereum L1 similar. Solana prioritises security + scalability (more centralised). Layer 2 solutions (Rollups, Lightning Network) attempt to achieve all three by handling computation off-chain.","explanation":"The trilemma explains why every 'Ethereum killer' that claims to solve all three simultaneously has made hidden trade-offs — usually in decentralisation, which is harder to measure but fundamental to the trust model.","topic":"Blockchain & Web3","caption":"Every new blockchain claiming to solve the trilemma needs to be scrutinised for where they actually made the trade-off. Speed without decentralisation is just a database. The trilemma isn't a bug in Satoshi's design — it's a fundamental constraint of distributed systems 🔗"},
    {"question":"What is transformer architecture and why did it revolutionise AI?","answer":"Transformers (Vaswani et al., 2017 — 'Attention Is All You Need') replaced recurrent networks with a self-attention mechanism that weighs the importance of different tokens relative to each other in parallel. Advantages: parallelisable (faster training), captures long-range dependencies better, scales with data and compute. Foundation of GPT, BERT, T5, and virtually all large language models.","explanation":"The transformer's scalability was the key insight. Unlike RNNs that struggled as sequences lengthened, transformers got better as you added more parameters and data — enabling the scaling laws that produced GPT-4.","topic":"Machine Learning","caption":"Re-reading 'Attention Is All You Need' and it's remarkable how one architecture paper fundamentally restructured an entire industry. The self-attention mechanism is so elegant that once you understand it, RNNs feel like hammers where we needed scalpels. Transformers changed everything."},
    {"question":"What are the core ethical concerns with large-scale AI deployment?","answer":"(1) Bias and fairness: models trained on biased data perpetuate/amplify discrimination (facial recognition, hiring algorithms). (2) Opacity: black-box models make consequential decisions without explainability. (3) Privacy: training on personal data, inference attacks. (4) Concentration of power: AI capabilities concentrate in a few corporations/states. (5) Misalignment: optimising for measurable proxies instead of true values. (6) Autonomous weapons: lethal AI without meaningful human control.","explanation":"These aren't theoretical — they're happening. Amazon's hiring algorithm discriminated against women. PredPol (police prediction) reinforced over-policing of minority communities. COMPAS recidivism scoring showed racial bias.","topic":"AI Ethics","caption":"AI ethics is not a PR exercise. Every concrete harm we're seeing — discriminatory hiring algorithms, biased facial recognition, manipulative recommender systems — was foreseeable and foreseen. The problem isn't that we didn't know. The problem is incentive structures that reward deployment speed over safety 🤖"},
  ],
  "Law": [
    {"question":"What is the doctrine of judicial review and how did it originate in the US?","answer":"Judicial review is the power of courts to invalidate laws or executive actions that violate the constitution. In the US, it was established in Marbury v. Madison (1803) by Chief Justice John Marshall — not explicitly granted by the Constitution, but derived from the logic that the Constitution is supreme law and courts must interpret law. Most democracies now have some form of constitutional review, either concentrated (constitutional court) or diffuse (any court).","explanation":"Marbury v. Madison is arguably the most consequential court decision in history. Without it, the US Constitution would be a political document, not a legal one.","topic":"Constitutional Law","caption":"Studying Marbury v. Madison again and what strikes me most is the audacity of the move. Marshall simultaneously denied Madison what he wanted AND established the Supreme Court's power to strike down acts of Congress — getting everything while appearing to give nothing. Legal genius as political chess ⚖️"},
    {"question":"What is the responsibility to protect (R2P) doctrine in international law?","answer":"R2P (adopted at UN World Summit 2005) holds that states have a responsibility to protect populations from genocide, war crimes, ethnic cleansing, and crimes against humanity. If a state fails to protect or is the perpetrator, the international community has a responsibility to intervene — through peaceful means first, then coercive measures (Security Council authorisation required). Critiques: selective application (Libya vs. Syria), sovereignty concerns, lack of enforcement.","explanation":"Libya (2011) was the first explicit R2P invocation — it turned into regime change, making Russia and China permanently more resistant to authorising future interventions under R2P.","topic":"Human Rights Law","caption":"R2P is one of the most contested ideas in international law. The principle is sound: sovereignty is not a shield for mass atrocities. The practice is broken: it's applied when geopolitically convenient and ignored when not. Syria is the graveyard of R2P as a meaningful doctrine. That's not an argument against the principle — it's an argument for fixing the mechanism."},
    {"question":"What is the difference between civil law and common law systems?","answer":"Common law (UK, US, Australia, most Commonwealth): judge-made law through precedent (stare decisis) is as important as statute. Cases develop legal rules organically. Adversarial court system. Civil law (continental Europe, Latin America, East Asia): comprehensive statutory codes are primary; judges apply code to facts rather than building doctrine through cases. Inquisitorial system. Mixed systems exist (South Africa, Scotland, Quebec).","explanation":"The distinction matters practically: in common law, reading cases is essential; in civil law, the code is everything. Legal training, court procedures, and even how contracts are drafted differ fundamentally.","topic":"Legal Philosophy","caption":"Studying comparative law this semester and the civil/common law distinction goes so much deeper than most people realise. It's not just about procedure — it's about entirely different theories of what law IS and where it comes from. Code vs. precedent is almost a philosophical difference about the nature of legal authority ⚖️"},
  ],
  "Philosophy": [
    {"question":"What is the hard problem of consciousness?","answer":"David Chalmers (1995) distinguished the 'easy problems' of consciousness (explaining cognitive functions: attention, memory, reportability) from the 'hard problem': why there is subjective experience at all — why physical processes give rise to a felt, first-person phenomenal quality ('what it is like to be'). The hard problem resists functional/computational explanation because you can imagine a functional duplicate with no inner experience ('philosophical zombie').","explanation":"The hard problem may be the deepest question in philosophy. It sits at the intersection of neuroscience, physics, and philosophy — and there is still no consensus on whether it has a scientific solution.","topic":"Philosophy of Mind","caption":"Chalmers' hard problem of consciousness is the question that keeps me up at night. We can explain every cognitive function — attention, memory, language — and still have explained nothing about why there's 'something it is like' to be you reading this. That explanatory gap might be the most profound mystery in all of philosophy 🤔"},
    {"question":"What is the trolley problem and what philosophical theories does it test?","answer":"The trolley problem (Foot, Thomson): a trolley is heading toward five people. You can divert it to kill one instead. Most say yes. The footbridge variant: you can push a large man off a bridge to stop the trolley and save five. Most say no. Tests: Consequentialism (results matter — divert) vs. Deontology (some acts are inherently wrong — don't push) vs. Virtue ethics (what would a virtuous person do?). Greene's neuroscience research shows the footbridge triggers emotional disgust while the switch version is more cognitive.","explanation":"The scenarios aren't just philosophical puzzles — they're tests of moral architecture. Why do physically identical outcomes feel morally different based on how you bring them about?","topic":"Ethics & Moral Philosophy","caption":"The trolley problem isn't about trolleys. It's about the architecture of our moral psychology — why we intuitively distinguish between doing and allowing harm, between intended and foreseen consequences. Joshua Greene's neuroimaging work showing these intuitions activate different brain systems is genuinely exciting 🧠"},
    {"question":"What is Rawls' veil of ignorance thought experiment?","answer":"John Rawls (A Theory of Justice, 1971): to determine just social principles, imagine choosing them from behind a 'veil of ignorance' — not knowing your place in society (class, talent, gender, race). From this 'original position,' Rawls argues rational people would choose: (1) Equal basic liberties for all; (2) Social/economic inequalities permitted only if they benefit the least advantaged (difference principle). The thought experiment grounds liberalism without appealing to utility.","explanation":"Rawls is arguing that justice requires impartiality, and impartiality is only truly achieved when you don't know what side of a policy you'll be on. It's a powerful rebuttal to 'I deserve what I have earned' arguments that ignore the role of luck.","topic":"Political Philosophy","caption":"The veil of ignorance is the single most powerful thought experiment in political philosophy in my opinion. If you didn't know whether you'd be born wealthy or poor, healthy or disabled, majority or minority — what society would you design? The answer tells you more about justice than any abstract principle 💭"},
  ],
  "Biology": [
    {"question":"What is CRISPR-Cas9 and how does it work?","answer":"CRISPR-Cas9 is a molecular tool derived from bacterial immune systems. Components: (1) Guide RNA (gRNA) — synthetic RNA matching the target DNA sequence; (2) Cas9 protein — molecular scissors that cuts double-stranded DNA at the target site. After cutting, the cell's repair mechanisms either disable the gene (NHEJ) or insert new sequences (HDR). Applications: correcting genetic diseases, creating animal models, agricultural improvements.","explanation":"Jennifer Doudna and Emmanuelle Charpentier won the 2020 Nobel Prize in Chemistry for developing CRISPR-Cas9. The first CRISPR treatment for sickle cell disease was approved by FDA in 2023.","topic":"Genetics","caption":"The FDA approval of CRISPR therapy for sickle cell disease in 2023 is the moment where gene editing stopped being theoretical for me. This is a disease that has caused immeasurable suffering for generations and we now have a functional cure. Understanding how Cas9 actually cuts is the foundation of understanding why this is revolutionary 🔬"},
    {"question":"What is the central dogma of molecular biology?","answer":"Proposed by Crick (1958): DNA → RNA → Protein. Information flows from DNA (storage) via transcription to RNA, then via translation to proteins (functional molecules). Important clarifications: reverse transcription (RNA → DNA) exists (retroviruses like HIV); RNA can be functional without being translated (rRNA, tRNA, microRNA); epigenetic information doesn't fit neatly into the dogma.","explanation":"The 'central dogma' is one of the most important concepts in all biology — and one of the most misnamed. It's not dogmatic — exceptions exist and the field has evolved significantly since Crick proposed it.","topic":"Molecular Biology","caption":"The central dogma is a beautiful starting point that becomes more fascinating the more you learn its exceptions. Retroviruses reverse it. RNA interference complicates the protein step. Prions arguably violate it entirely. The exceptions reveal more about biology than the rule itself 🧬"},
    {"question":"What is natural selection and what conditions are required for it to operate?","answer":"Natural selection: differential survival and reproduction of individuals with heritable traits better suited to their environment. Required conditions (Darwin): (1) Variation — individuals differ in traits; (2) Heritability — traits are passed to offspring; (3) Differential fitness — traits affect survival/reproduction. Over generations, favourable traits increase in frequency. Natural selection is one of four evolutionary mechanisms alongside genetic drift, mutation, and gene flow.","explanation":"Evolution by natural selection doesn't have goals or direction — it's a filtering mechanism. Traits that happen to improve survival/reproduction in current conditions spread. Conditions change, optimal traits change.","topic":"Genetics","caption":"Evolution by natural selection is the most powerful explanatory idea in all of science and it's still regularly misunderstood. 'Survival of the fittest' is almost always misquoted — fitness means reproductive success in the current environment, not strength or intelligence. A bacterium with antibiotic resistance is more 'fit' than a human in penicillin solution 🦠"},
  ],
  "Chemistry": [
    {"question":"What makes carbon the basis of life and what is unique about its chemistry?","answer":"Carbon's uniqueness: (1) Forms 4 stable covalent bonds — maximum connectivity; (2) Bonds with itself in chains, rings, branched structures (catenation) — enabling infinite molecular diversity; (3) Forms stable bonds with H, O, N, S — the other key elements of life; (4) Double and triple bonds enable functional group diversity. No other element approaches carbon's combinatorial versatility at biological temperatures.","explanation":"Silicon can also form 4 bonds and is abundant, but Si-Si and Si-O bonds don't have the same stability or flexibility at Earth temperatures. This is why carbon-based life is likely universal across similar environments.","topic":"Biochemistry","caption":"Organic chemistry humbled me more than any other subject in my degree. But once you see carbon's combinatorial logic — the way 4 bonds + catenation + functional groups creates essentially infinite molecular space — you understand why life couldn't have been built from anything else. Carbon is inevitable 🧪"},
    {"question":"What is Le Chatelier's Principle and how is it applied in industrial chemistry?","answer":"Le Chatelier's Principle: when a system at equilibrium is disturbed, it shifts to oppose the disturbance and restore equilibrium. Applications: Haber Process (NH3 synthesis) — high pressure favours product side (fewer moles of gas); lower temperature favours NH3 (exothermic reaction), but kinetics require a compromise temperature (~450°C); catalyst doesn't shift equilibrium but speeds up attainment. Contact Process (SO3/H2SO4 production) — similar principles.","explanation":"The Haber Process, designed using Le Chatelier's principles, produces fertiliser for ~50% of Earth's current population. Possibly the most consequential application of chemistry in human history.","topic":"Organic Chemistry","caption":"The Haber Process is one of the most important chemical reactions in human history — we synthesise enough ammonia to feed half the world's population. And it's fundamentally an exercise in applying Le Chatelier's principle under industrial constraints. Chemistry saves lives at scale 🏭"},
  ],
  "Literature": [
    {"question":"What are the central themes of Chinua Achebe's Things Fall Apart and why did it matter?","answer":"Things Fall Apart (1958) explores the clash between Igbo culture and British colonialism through Okonkwo's story. Themes: cultural change and resilience, masculinity and identity, tradition vs. modernity, the complexity of indigenous society (rejecting the 'primitive Africa' narrative), the psychological violence of colonisation. Its importance: first major African novel to depict pre-colonial African society with internal complexity, written in English that incorporated Igbo rhythms and proverbs. Directly challenged Conrad's Heart of Darkness.","explanation":"Achebe's essay 'An Image of Africa' (1977) argued that Conrad's novel was racist in its depiction of Africans as backdrop to a European psychological drama. Things Fall Apart was in part a counter-narrative.","topic":"African Literature","caption":"Re-reading Things Fall Apart for the third time and it only gets richer. What Achebe achieved in 1958 — depicting Igbo civilisation as internally complex, contradictory, fully human, before Europeans arrive to disrupt it — was a radical act. He wrote Africa back into its own story. 📚 Required reading, full stop."},
    {"question":"What is magical realism and how does García Márquez use it in One Hundred Years of Solitude?","answer":"Magical realism: a literary mode where magical elements appear in an otherwise realistic narrative without being treated as unusual — they're accepted as part of ordinary reality. García Márquez: Macondo's founding, the Buendía family's multigenerational curse, ghosts of the dead coexisting with the living, a rain of yellow flowers, Remedios the Beauty ascending to heaven. The technique allows exploration of Latin American history (colonial trauma, civil wars, United Fruit Company massacre) through mythic rather than documentary register.","explanation":"Magical realism isn't escapism — it's a way of encoding historical trauma and cultural experience that resists being captured by conventional realism. Marquez said he was simply describing what he heard from his grandmother.","topic":"Comparative Literature","caption":"Started One Hundred Years of Solitude for the first time and the opening line — 'Many years later, as he faced the firing squad...' — might be the most perfect opening in world literature. García Márquez understood that Latin American history is so extreme it requires a hyper-real register to communicate it truthfully 📖"},
  ],
  "Sociology": [
    {"question":"What is Bourdieu's concept of cultural capital and how does it reproduce inequality?","answer":"Bourdieu identified three types of capital: economic (money/assets), social (networks/connections), and cultural (knowledge, skills, cultural competencies valued by dominant classes). Cultural capital exists in embodied form (dispositions, tastes), objectified form (books, art), and institutionalised form (degrees). Schools appear meritocratic but actually reward students whose families have provided cultural capital — reproducing class inequality while appearing to measure individual merit.","explanation":"Bourdieu's insight: educational systems don't just transmit knowledge — they legitimise certain knowledge and ways of knowing as 'excellence,' then reward those who arrived already possessing them.","topic":"Social Inequality","caption":"Bourdieu changed how I see education entirely. When we say someone 'doesn't belong' in elite spaces or 'doesn't work hard enough,' we're often describing differential access to cultural capital — which is the product of class, not individual merit. The meritocracy myth is one of sociology's most important targets 🎓"},
    {"question":"What is Foucault's concept of power-knowledge and why does it matter?","answer":"Foucault argued that knowledge and power are inseparable — power produces knowledge and knowledge constitutes power. Those who control what counts as 'truth' in a society (psychiatrists defining madness, criminologists defining crime, doctors defining health) exercise power by defining norms and excluding deviants. Power is not just repressive (saying no) but productive — it creates categories, subjects, behaviours.","explanation":"Foucault's genealogical method: instead of asking 'what is the truth about madness/sexuality/crime?' ask 'how did this category come to be? Who benefits from it?'. Discourses are political.","topic":"Cultural Studies","caption":"Reading Foucault's Discipline and Punish during a week when I've been following surveillance technology debates — the parallel between Bentham's panopticon and modern data collection is so obvious it's almost too on-the-nose. We built a digital panopticon and called it social media. Power through visibility hasn't changed — just the architecture 🏛️"},
  ],
  "Business": [
    {"question":"What is Clayton Christensen's theory of disruptive innovation?","answer":"Disruptive innovation: a process where a product/service initially takes root in simple or low-cost applications (ignored by incumbents focused on high-margin customers) and then relentlessly moves upmarket, eventually displacing established competitors. Classic examples: transistor radios vs. tabletop radios; Netflix vs. Blockbuster; smartphones vs. digital cameras. Incumbents fail not from incompetence but from rationally serving their best customers while the disruptor builds from below.","explanation":"The theory explains why smart, well-managed companies get beaten. They are rational actors responding to their most profitable customers — the same rationality that makes them successful makes them vulnerable to disruption from below.","topic":"Entrepreneurship","caption":"Christensen's disruption theory explains why the smartest incumbents still lose. Blockbuster made the right decision for their shareholders every quarter right up until they didn't exist. Being rational toward your current customers is the very thing that makes you vulnerable. This is the trap every successful company eventually faces 🏢"},
    {"question":"What is the difference between a startup's vision, mission, and strategy?","answer":"Vision: the future state you're trying to create (why the company exists beyond profit). Mission: what you specifically do to pursue that vision (your core activity). Strategy: how you allocate resources to achieve competitive advantage. Common mistake: confusing strategy with goals — 'grow revenue 30%' is a goal, not a strategy. Strategy involves choices about where to compete, how to win, and what trade-offs to make. Good strategy explicitly says what you will NOT do.","explanation":"Richard Rumelt in 'Good Strategy Bad Strategy': most 'strategies' are just aspirations dressed in business jargon. A real strategy has a diagnosis, a guiding policy, and coherent actions. Very few companies actually have one.","topic":"Entrepreneurship","caption":"Had a strategy session at my startup this week and realised we'd been confusing goals with strategy for months. 'Become market leader in X' is not a strategy. WHO are you targeting, HOW are you different, WHAT are you NOT doing — those are strategy questions. Rumelt's framework is brutal and essential 📈"},
    {"question":"What is unit economics and why is it critical for startups?","answer":"Unit economics: the direct revenues and costs associated with a single unit of a business model (one customer, one transaction, one subscription). Key metrics: Customer Acquisition Cost (CAC) — how much to acquire one customer; Lifetime Value (LTV) — total profit from one customer over their relationship with you. LTV/CAC > 3 is typically sustainable. Payback period: how long to recoup CAC from gross margin. Startups burning cash without positive unit economics are building on sand.","explanation":"WeWork had terrible unit economics — each new location cost more than it generated. This wasn't hidden; it was obscured by growth metrics. Investors who didn't do the unit economics math lost billions.","topic":"Tech Startups & VC","caption":"Unit economics is the single most important concept for evaluating any business. Every 'growth at all costs' story that ended badly was really a unit economics story — someone was paying $200 to acquire a customer who generated $80 of lifetime value and calling it a business. LTV/CAC is not optional knowledge for founders 📉"},
  ],
  "Journalism": [
    {"question":"What is the difference between misinformation, disinformation, and malinformation?","answer":"Misinformation: false content shared without intent to harm (the sharer believes it's true). Disinformation: false content created and shared with deliberate intent to deceive. Malinformation: truthful content used with intent to cause harm (e.g., private photos shared to harass). These distinctions matter because solutions differ: misinformation needs media literacy; disinformation needs platform regulation and legal frameworks; malinformation needs privacy law.","explanation":"Much public discourse conflates these — treating all 'fake news' as the same problem. The First Draft framework (now First Draft News) made these distinctions standard in journalism research.","topic":"Media & Society","caption":"The misinformation/disinformation distinction should be taught everywhere. When your aunt shares health misinformation, she genuinely believes it — the solution is different from state-sponsored disinformation campaigns designed by professionals. Treating them the same produces wrong interventions. Precision matters in this fight 📰"},
  ],
  "Public Health": [
    {"question":"What is herd immunity and what threshold is required for different diseases?","answer":"Herd immunity: when enough of a population is immune (through infection or vaccination) that disease transmission is interrupted, protecting those who can't be immunised. Threshold depends on the basic reproduction number R0: herd immunity threshold = 1 − 1/R0. Measles: R0≈15, threshold ~93%. Polio: R0≈5-7, threshold ~80-86%. COVID-19 original strain: R0≈2.5, threshold ~60% (though variants with higher R0 raised this). Herd immunity through natural infection carries enormous mortality cost.","explanation":"The reason vaccination is the only ethical route to herd immunity for highly infectious diseases: the death toll of achieving it through natural infection is simply unacceptable.","topic":"Epidemiology","caption":"The herd immunity debate during COVID-19 was one of the most important and most poorly communicated scientific concepts of the pandemic. The mathematics are not optional — if you don't vaccinate enough people, the virus continues to circulate and find vulnerable hosts. Every percentage below threshold represents real deaths. 💉"},
  ],
  "Finance": [
    {"question":"What caused the 2008 global financial crisis?","answer":"Key causes: (1) Housing bubble — loose lending standards, predatory mortgages, assumption prices always rise. (2) Securitisation — mortgages bundled into MBS/CDOs, risk obscured and widely distributed. (3) Rating agency failure — AAA ratings given to toxic assets for fee income. (4) Leverage — banks held insufficient capital against huge risk positions. (5) Regulatory failure — shadow banking system outside prudential oversight. (6) Contagion — global financial integration meant US mortgage defaults collapsed institutions worldwide.","explanation":"The crisis was not a black swan. It was predictable and predicted by several economists (Rajan at Jackson Hole 2005, Roubini, Shiller). The failure was institutional and incentive-driven, not epistemic.","topic":"Financial Markets","caption":"Studying the 2008 crisis and what's most striking is how many people saw it coming and were ignored. Rajan presented at Jackson Hole in 2005 warning about exactly the incentive structures that caused the crash — and was dismissed as a luddite. Risk that is profitable to ignore gets ignored. That hasn't changed. 📊"},
  ],
  "International Relations": [
    {"question":"What is the security dilemma and why does it make peace hard to maintain?","answer":"The security dilemma: actions a state takes to increase its own security (arming, building alliances) are perceived as threats by other states, causing them to arm in response, making the original state less secure. Classic spiral dynamic. Examples: NATO expansion and Russian threat perception; US-China naval competition in South China Sea; India-Pakistan nuclear deterrence. Solutions: transparency measures, arms control treaties, concert of powers — all difficult to sustain.","explanation":"The security dilemma doesn't require bad intentions — even benign defensive actions can trigger dangerous spirals. This is why international relations is so difficult even when leaders want peace.","topic":"China & Global Order","caption":"The Russia-Ukraine war is partly a security dilemma story — NATO expansion was defensive from Western perspective, existential from Russian perspective. Whether you find that explanation convincing or apologetic, understanding the security dilemma mechanism is essential for understanding how security crises develop. Neither side needs to be evil for the spiral to happen."},
  ],
}

# Fallback cards for subjects not explicitly listed
FALLBACK_CARDS = [
  {"question":"What are the most important study techniques supported by cognitive science?","answer":"Evidence-based techniques: (1) Spaced repetition — reviewing material at increasing intervals exploits the spacing effect; (2) Retrieval practice — testing yourself (not re-reading) is the most effective consolidation method; (3) Interleaving — mixing topics rather than blocked practice improves transfer; (4) Elaborative interrogation — asking 'why' forces deeper processing; (5) Concrete examples — connecting abstract concepts to specific instances aids retention.","explanation":"Re-reading and highlighting feel productive but have weak empirical support. Retrieval practice (the testing effect) is consistently the most powerful technique across subjects and ages.","topic":"Study Skills","caption":"Changed my entire study method last semester based on the cognitive science literature and my results improved dramatically. Retrieval practice over re-reading. Spaced repetition over cramming. It's not about studying more — it's about studying in alignment with how memory actually works 📚"},
  {"question":"What is compounding and why did Einstein allegedly call it the eighth wonder of the world?","answer":"Compounding: earning returns on both principal AND previously earned returns. Formula: A = P(1+r)^t. At 10% annual return: $1,000 becomes $2,594 in 10 years, $6,727 in 20 years, $17,449 in 30 years. The growth is exponential, not linear — time is the dominant variable. This applies to debt (credit cards compound against you), skills (knowledge compounds), and relationships.","explanation":"The reason starting early is so powerful: the first 10 years may add less than the last 10 years in absolute terms, but they're the necessary foundation for exponential growth.","topic":"Personal Finance","caption":"Showed a friend the compounding calculation this week and watched their eyes go wide. The maths of compounding is something every teenager should understand before they leave school. Time is the variable that most people waste — both with money and with learning 💰"},
  {"question":"What is critical thinking and how do you apply it to everyday claims?","answer":"Critical thinking: disciplined analysis of claims using evidence, logic, and intellectual humility. Framework: (1) What is the claim? (2) What is the evidence? (3) Is the source credible? (4) What are alternative explanations? (5) Am I motivated to believe this? (cognitive bias check). (6) What would change my mind? (falsifiability). Applied: before sharing information, ask who made it, why, with what evidence.","explanation":"Critical thinking is a meta-skill that applies across every domain. The inability to critically evaluate claims is arguably the most dangerous form of illiteracy in an information-saturated world.","topic":"Logic & Reasoning","caption":"Critical thinking is not cynicism — it's structured curiosity. It's asking 'how do we know this?' before 'what does this mean?' Teaching this skill should be the primary purpose of education. Everything else is content; this is the container 🧠"},
]

async def main():
    print(f"Connecting to {DB_NAME}...")
    client = AsyncIOMotorClient(MONGODB_URL)
    db = client[DB_NAME]

    existing_emails = set()
    async for u in db.users.find({}, {"email": 1}):
        existing_emails.add(u["email"])

    created_users = 0
    created_cards = 0

    for i, persona in enumerate(PERSONAS):
        email = persona["email"]
        if email in existing_emails:
            print(f"  skip {persona['username']} (exists)")
            continue

        # Create user
        uid = ObjectId()
        days_ago = random.randint(10, 180)
        created_at = datetime.utcnow() - timedelta(days=days_ago)
        points = random.randint(150, 8500)
        streak = random.randint(0, 67)

        user_doc = {
            "_id": uid,
            "email": email,
            "username": persona["username"],
            "full_name": persona["name"],
            "hashed_password": None,
            "auth_provider": "google",
            "provider_id": f"bot_{uid}",
            "profile_picture": f"https://i.pravatar.cc/300?img={persona['img']}",
            "role": "user",
            "is_bot": True,
            "is_active": True,
            "is_verified": random.random() > 0.6,
            "onboarding_completed": True,
            "total_points": points,
            "level": min(10, points // 1000 + 1),
            "current_streak": streak,
            "longest_streak": streak + random.randint(0, 30),
            "followers_count": random.randint(0, 50),
            "following_count": random.randint(5, 80),
            "subjects": [persona["subject"]],
            "education_level": random.choice(["undergraduate", "postgraduate", "phd", "undergraduate"]),
            "created_at": created_at,
            "last_login": datetime.utcnow() - timedelta(days=random.randint(0, 5)),
        }
        await db.users.insert_one(user_doc)
        created_users += 1

        # Pick cards for this subject
        subject = persona["subject"]
        card_pool = CARDS_BY_SUBJECT.get(subject, FALLBACK_CARDS)
        # Use fallback if less than 2 cards available
        if len(card_pool) < 2:
            card_pool = FALLBACK_CARDS
        num_cards = random.randint(min(4, len(card_pool)), min(8, len(card_pool)))
        selected = random.sample(card_pool, num_cards)

        for j, card_data in enumerate(selected):
            card_created = created_at + timedelta(days=random.randint(0, days_ago))
            card_doc = {
                "_id": ObjectId(),
                "question": card_data["question"],
                "answer": card_data["answer"],
                "explanation": card_data.get("explanation", ""),
                "subject": subject,
                "topic": card_data.get("topic", persona["topic"]),
                "tags": [subject.lower(), card_data.get("topic","").lower()],
                "visibility": "public",
                "caption": card_data.get("caption", ""),
                "created_by": str(uid),
                "author_username": persona["username"],
                "author_full_name": persona["name"],
                "author_profile_picture": f"https://i.pravatar.cc/300?img={persona['img']}",
                "user_id": str(uid),
                "likes": random.randint(0, 180),
                "views": random.randint(20, 2000),
                "saves": random.randint(0, 50),
                "comments_count": random.randint(0, 25),
                "is_active": True,
                "mastery_level": 0,
                "ease_factor": 2.5,
                "interval": 1,
                "next_review": None,
                "created_at": card_created,
                "updated_at": card_created,
            }
            await db.cards.insert_one(card_doc)
            created_cards += 1

        print(f"  ✓ {persona['username']} ({subject}) — {num_cards} cards")

    client.close()
    print(f"\nDone. Created {created_users} users, {created_cards} cards.")

asyncio.run(main())
