from typing import List, Dict, Optional
from app.models.user import User
from app.models.card import Card
from app.services.card_repository import CardRepository
import random
from datetime import datetime

class PersonalizedFeedService:
    """
    Generates personalized feed of cards based on user profile and behavior.

    Feed Mix Algorithm:
    - 50% User's enrolled subjects (AI-generated by subject)
    - 20% Based on search/question history (topics user studied)
    - 15% Spaced repetition (cards due for review)
    - 10% Trending in user's subjects
    - 5% Discover (new topics, random public cards)
    """

    @staticmethod
    async def get_personalized_feed(
        user: User,
        limit: int = 50,
        offset: int = 0
    ) -> List[Card]:
        """
        Generate personalized feed for user.

        Args:
            user: User object with profile data
            limit: Number of cards to return
            offset: Pagination offset

        Returns:
            List of cards personalized for the user
        """

        feed_cards = []

        # Calculate target counts based on mix percentages
        target_counts = {
            'subjects': int(limit * 0.50),      # 50% from enrolled subjects
            'history': int(limit * 0.20),       # 20% from history
            'review': int(limit * 0.15),        # 15% due for review
            'trending': int(limit * 0.10),      # 10% trending
            'discover': limit - int(limit * 0.95)  # 5% discover (remaining)
        }

        # 1. Cards from user's enrolled subjects (50%)
        if user.subjects:
            subject_cards = await PersonalizedFeedService._get_subject_cards(
                user,
                target_counts['subjects']
            )
            feed_cards.extend(subject_cards)

        # 2. Cards based on search/question history (20%)
        # TODO: Track user history and implement this
        # For now, get cards from similar topics
        history_cards = await PersonalizedFeedService._get_history_based_cards(
            user,
            target_counts['history']
        )
        feed_cards.extend(history_cards)

        # 3. Spaced repetition - due cards (15%)
        review_cards = await CardRepository.get_due_cards(user.id, target_counts['review'])
        feed_cards.extend(review_cards)

        # 4. Trending in user's subjects (10%)
        trending_cards = await PersonalizedFeedService._get_trending_in_subjects(
            user,
            target_counts['trending']
        )
        feed_cards.extend(trending_cards)

        # 5. Discover new topics (5%)
        discover_cards = await PersonalizedFeedService._get_discover_cards(
            user,
            target_counts['discover']
        )
        feed_cards.extend(discover_cards)

        # Remove duplicates (keep first occurrence)
        seen_ids = set()
        unique_cards = []
        for card in feed_cards:
            if card.id not in seen_ids:
                seen_ids.add(card.id)
                unique_cards.append(card)

        # Shuffle to mix different sources
        random.shuffle(unique_cards)

        # Apply pagination
        return unique_cards[offset:offset + limit]

    @staticmethod
    async def _get_subject_cards(user: User, limit: int) -> List[Card]:
        """Get public cards from user's enrolled subjects"""
        if not user.subjects:
            return []

        cards = await CardRepository.get_trending_cards(limit * 2)  # Get more to filter

        # Filter cards matching user's subjects
        subject_cards = [
            card for card in cards
            if card.subject and card.subject.lower() in [s.lower() for s in user.subjects]
        ]

        return subject_cards[:limit]

    @staticmethod
    async def _get_history_based_cards(user: User, limit: int) -> List[Card]:
        """
        Get cards based on user's search and question history.

        TODO: Implement history tracking
        For now, returns cards from topics user has studied
        """
        # Get user's own cards to identify topics they've studied
        user_cards = await CardRepository.get_user_cards(
            user.id,
            limit=50
        )

        if not user_cards:
            return []

        # Extract topics user has studied
        studied_topics = set()
        for card in user_cards:
            if card.topic:
                studied_topics.add(card.topic.lower())

        if not studied_topics:
            return []

        # Get public cards with similar topics
        all_cards = await CardRepository.get_trending_cards(limit * 3)

        matching_cards = [
            card for card in all_cards
            if card.topic and card.topic.lower() in studied_topics
            and card.user_id != user.id  # Don't include own cards
        ]

        return matching_cards[:limit]

    @staticmethod
    async def _get_trending_in_subjects(user: User, limit: int) -> List[Card]:
        """Get trending cards specifically in user's subjects"""
        if not user.subjects:
            return []

        trending = await CardRepository.get_trending_cards(limit * 2)

        # Filter for user's subjects
        subject_trending = [
            card for card in trending
            if card.subject and card.subject.lower() in [s.lower() for s in user.subjects]
        ]

        return subject_trending[:limit]

    @staticmethod
    async def _get_discover_cards(user: User, limit: int) -> List[Card]:
        """
        Get discovery cards - new topics outside user's normal subjects.
        Helps users explore and expand their learning.
        """
        all_trending = await CardRepository.get_trending_cards(limit * 4)

        # Filter for cards NOT in user's subjects (new topics)
        user_subject_ids = [s.lower() for s in (user.subjects or [])]

        discover = [
            card for card in all_trending
            if not card.subject or card.subject.lower() not in user_subject_ids
        ]

        return discover[:limit]

    @staticmethod
    async def get_feed_insights(user: User) -> Dict:
        """
        Get insights about user's feed composition.
        Useful for analytics and showing user what they're learning.
        """

        # Get sample feed
        feed = await PersonalizedFeedService.get_personalized_feed(user, limit=50)

        # Analyze composition
        subjects_count = {}
        topics_count = {}

        for card in feed:
            if card.subject:
                subjects_count[card.subject] = subjects_count.get(card.subject, 0) + 1
            if card.topic:
                topics_count[card.topic] = topics_count.get(card.topic, 0) + 1

        return {
            'total_cards': len(feed),
            'subjects': subjects_count,
            'topics': topics_count,
            'enrolled_subjects': user.subjects or [],
            'feed_quality': 'personalized' if user.subjects else 'general'
        }

# Global instance
personalized_feed_service = PersonalizedFeedService()
